// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1591.Steamworks;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.smartdashboard.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainSpeedControllerFL;
    public static Encoder driveTrainEncoderFL;
    public static PIDController driveTrainFrontLeft;
    public static SpeedController driveTrainSpeedControllerFR;
    public static Encoder driveTrainEncoderFR;
    public static PIDController driveTrainFrontRight;
    public static SpeedController driveTrainSpeedControllerBL;
    public static Encoder driveTrainEncoderBL;
    public static PIDController driveTrainBackLeft;
    public static SpeedController driveTrainSpeedControllerBR;
    public static Encoder driveTrainEncoderBR;
    public static PIDController driveTrainBackRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainSpeedControllerFL = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "SpeedControllerFL", (Talon) driveTrainSpeedControllerFL);
        
        driveTrainEncoderFL = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "EncoderFL", driveTrainEncoderFL);
        driveTrainEncoderFL.setDistancePerPulse(1.0);
        driveTrainEncoderFL.setPIDSourceType(PIDSourceType.kRate);
        driveTrainFrontLeft = new PIDController(1.0, 0.0, 0.0, 0.0, driveTrainEncoderFL, driveTrainSpeedControllerFL, 0.02);
        LiveWindow.addActuator("DriveTrain", "FrontLeft", driveTrainFrontLeft);
        driveTrainFrontLeft.setContinuous(false);
        driveTrainFrontLeft.setAbsoluteTolerance(0.2);

        driveTrainFrontLeft.setOutputRange(-1.0, 1.0);
        driveTrainSpeedControllerFR = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "SpeedControllerFR", (Talon) driveTrainSpeedControllerFR);
        
        driveTrainEncoderFR = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "EncoderFR", driveTrainEncoderFR);
        driveTrainEncoderFR.setDistancePerPulse(1.0);
        driveTrainEncoderFR.setPIDSourceType(PIDSourceType.kRate);
        driveTrainFrontRight = new PIDController(1.0, 0.0, 0.0, 0.0, driveTrainEncoderFR, driveTrainSpeedControllerFR, 0.02);
        LiveWindow.addActuator("DriveTrain", "FrontRight", driveTrainFrontRight);
        driveTrainFrontRight.setContinuous(false);
        driveTrainFrontRight.setAbsoluteTolerance(0.2);

        driveTrainFrontRight.setOutputRange(-1.0, 1.0);
        driveTrainSpeedControllerBL = new Talon(4);
        LiveWindow.addActuator("DriveTrain", "SpeedControllerBL", (Talon) driveTrainSpeedControllerBL);
        
        driveTrainEncoderBL = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "EncoderBL", driveTrainEncoderBL);
        driveTrainEncoderBL.setDistancePerPulse(1.0);
        driveTrainEncoderBL.setPIDSourceType(PIDSourceType.kRate);
        driveTrainBackLeft = new PIDController(1.0, 0.0, 0.0, 0.0, driveTrainEncoderBL, driveTrainSpeedControllerBL, 0.02);
        LiveWindow.addActuator("DriveTrain", "BackLeft", driveTrainBackLeft);
        driveTrainBackLeft.setContinuous(false);
        driveTrainBackLeft.setAbsoluteTolerance(0.2);

        driveTrainBackLeft.setOutputRange(-1.0, 1.0);
        driveTrainSpeedControllerBR = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "SpeedControllerBR", (Talon) driveTrainSpeedControllerBR);
        
        driveTrainEncoderBR = new Encoder(6, 7, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "EncoderBR", driveTrainEncoderBR);
        driveTrainEncoderBR.setDistancePerPulse(1.0);
        driveTrainEncoderBR.setPIDSourceType(PIDSourceType.kRate);
        driveTrainBackRight = new PIDController(1.0, 0.0, 0.0, 0.0, driveTrainEncoderBR, driveTrainSpeedControllerBR, 0.02);
        LiveWindow.addActuator("DriveTrain", "BackRight", driveTrainBackRight);
        driveTrainBackRight.setContinuous(false);
        driveTrainBackRight.setAbsoluteTolerance(0.2);

        driveTrainBackRight.setOutputRange(-1.0, 1.0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
