// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.Steamworks2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainCANTalonBR;
    public static CANTalon driveTrainCANTalonFR;
    public static CANTalon driveTrainCANTalonBL;
    public static CANTalon driveTrainCANTalonFL;
    public static RobotDrive driveTrainRobotDrive;
    public static CANTalon winchWinch;
    public static DigitalInput flapUpperLimitFlap;
    public static DigitalInput flapLowerLimitFlap;
    public static SpeedController flapFlapSC;
    public static DigitalInput gearPlungerBackPlungerLimit;
    public static SpeedController gearPlungerGearSC;
    public static DigitalInput gearPlungerFrontPlungerLimit;
    public static DigitalInput gearPlungerPositionSwitch;
    public static AnalogInput rangeFinderSonarAI;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainCANTalonBR = new CANTalon(7);
        LiveWindow.addActuator("DriveTrain", "CANTalonBR", driveTrainCANTalonBR);
        
        driveTrainCANTalonFR = new CANTalon(6);
        LiveWindow.addActuator("DriveTrain", "CANTalonFR", driveTrainCANTalonFR);
        
        driveTrainCANTalonBL = new CANTalon(4);
        LiveWindow.addActuator("DriveTrain", "CANTalonBL", driveTrainCANTalonBL);
        
        driveTrainCANTalonFL = new CANTalon(5);
        LiveWindow.addActuator("DriveTrain", "CANTalonFL", driveTrainCANTalonFL);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainCANTalonBR, driveTrainCANTalonBL,
              driveTrainCANTalonFR, driveTrainCANTalonFL);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);
        driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        winchWinch = new CANTalon(3);
        LiveWindow.addActuator("Winch", "Winch", winchWinch);
        
        flapUpperLimitFlap = new DigitalInput(0);
        LiveWindow.addSensor("Flap", "UpperLimitFlap", flapUpperLimitFlap);
        
        flapLowerLimitFlap = new DigitalInput(1);
        LiveWindow.addSensor("Flap", "LowerLimitFlap", flapLowerLimitFlap);
        
        flapFlapSC = new Spark(0);
        LiveWindow.addActuator("Flap", "FlapSC", (Spark) flapFlapSC);
        
        gearPlungerBackPlungerLimit = new DigitalInput(2);
        LiveWindow.addSensor("GearPlunger", "BackPlungerLimit", gearPlungerBackPlungerLimit);
        
        gearPlungerGearSC = new Spark(1);
        LiveWindow.addActuator("GearPlunger", "GearSC", (Spark) gearPlungerGearSC);
        
        gearPlungerFrontPlungerLimit = new DigitalInput(3);
        LiveWindow.addSensor("GearPlunger", "FrontPlungerLimit", gearPlungerFrontPlungerLimit);
        
        gearPlungerPositionSwitch = new DigitalInput(4);
        LiveWindow.addSensor("GearPlunger", "PositionSwitch", gearPlungerPositionSwitch);
        
        rangeFinderSonarAI = new AnalogInput(1);
        LiveWindow.addSensor("RangeFinder", "SonarAI", rangeFinderSonarAI);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	}
}
