// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1591.Steamworks.subsystems;

import org.usfirst.frc1591.Steamworks.RobotMap;
import org.usfirst.frc1591.Steamworks.commands.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.smartdashboard.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController speedControllerFL = RobotMap.driveTrainSpeedControllerFL;
    private final Encoder encoderFL = RobotMap.driveTrainEncoderFL;
    private final PIDController frontLeft = RobotMap.driveTrainFrontLeft;
    private final SpeedController speedControllerFR = RobotMap.driveTrainSpeedControllerFR;
    private final Encoder encoderFR = RobotMap.driveTrainEncoderFR;
    private final PIDController frontRight = RobotMap.driveTrainFrontRight;
    private final SpeedController speedControllerBL = RobotMap.driveTrainSpeedControllerBL;
    private final Encoder encoderBL = RobotMap.driveTrainEncoderBL;
    private final PIDController backLeft = RobotMap.driveTrainBackLeft;
    private final SpeedController speedControllerBR = RobotMap.driveTrainSpeedControllerBR;
    private final Encoder encoderBR = RobotMap.driveTrainEncoderBR;
    private final PIDController backRight = RobotMap.driveTrainBackRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

	public void driveStraight(double m_speed) {
		// TODO Auto-generated method stub
		
	}
}

